# Site settings
title:          HepCode
description:    "Sharing my experience with codes"
baseurl:        ""
url:            "https://heppcode.github.io"

# Author
author:
  name:         Bernard Nongpoh
  url:          https://heppcode.github.io
  email:        bernard.nongpoh@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
